#include <cstdint>
#include <cstdio>

#include <cuda_runtime.h>

#ifndef FLASHATTENTION_DISABLE_SM80
extern "C" void run_mha_sm80(
    void *q_ptr,
    void *k_ptr,
    void *v_ptr,
    void *page_table_ptr,
    void *o_ptr,
    void *softmax_lse_ptr,
    int32_t *cu_seqlens_q_ptr,
    int32_t *cu_seqlens_k_ptr,
    int32_t *seqused_q_ptr,
    int32_t *seqused_k_ptr,
    int32_t *leftpad_k_ptr,
    int32_t *kv_batch_idx_ptr,
    float *q_descale_ptr,
    float *k_descale_ptr,
    float *v_descale_ptr,
    uint32_t q_batch_stride,
    uint32_t k_batch_stride,
    uint32_t v_batch_stride,
    uint32_t o_batch_stride,
    uint32_t q_row_stride,
    uint32_t k_row_stride,
    uint32_t v_row_stride,
    uint32_t o_row_stride,
    uint32_t q_head_stride,
    uint32_t k_head_stride,
    uint32_t v_head_stride,
    uint32_t o_head_stride,
    uint32_t v_dim_stride,
    uint32_t q_descale_batch_stride,
    uint32_t q_descale_head_stride,
    uint32_t k_descale_batch_stride,
    uint32_t k_descale_head_stride,
    uint32_t v_descale_batch_stride,
    uint32_t v_descale_head_stride,
    uint32_t b,
    uint32_t b_k,
    uint32_t h,
    uint32_t h_k,
    uint32_t d,
    uint32_t dv,
    uint32_t seqlen_q,
    uint32_t seqlen_k,
    uint32_t total_q,
    uint32_t total_k,
    float softmax_scale,
    int is_bf16,
    int is_e4m3,
    int window_size_left,
    int window_size_right,
    int attention_chunk,
    int page_size,
    uint32_t page_table_batch_stride,
    int num_pages,
    int num_splits,
    void *softmax_lseaccum_ptr,
    void *oaccum_ptr,
    uint32_t oaccum_split_stride,
    uint32_t oaccum_batch_stride,
    uint32_t oaccum_row_stride,
    uint32_t oaccum_head_stride,
    uint32_t lseaccum_split_stride,
    uint32_t lseaccum_batch_stride,
    uint32_t lseaccum_head_stride,
    float softcap,
    int pack_gqa,
    int64_t cu_stream
);

extern "C" void run_mha_sm80_softcap(
    void *q_ptr,
    void *k_ptr,
    void *v_ptr,
    void *page_table_ptr,
    void *o_ptr,
    void *softmax_lse_ptr,
    int32_t *cu_seqlens_q_ptr,
    int32_t *cu_seqlens_k_ptr,
    int32_t *seqused_q_ptr,
    int32_t *seqused_k_ptr,
    int32_t *leftpad_k_ptr,
    int32_t *kv_batch_idx_ptr,
    float *q_descale_ptr,
    float *k_descale_ptr,
    float *v_descale_ptr,
    uint32_t q_batch_stride,
    uint32_t k_batch_stride,
    uint32_t v_batch_stride,
    uint32_t o_batch_stride,
    uint32_t q_row_stride,
    uint32_t k_row_stride,
    uint32_t v_row_stride,
    uint32_t o_row_stride,
    uint32_t q_head_stride,
    uint32_t k_head_stride,
    uint32_t v_head_stride,
    uint32_t o_head_stride,
    uint32_t v_dim_stride,
    uint32_t q_descale_batch_stride,
    uint32_t q_descale_head_stride,
    uint32_t k_descale_batch_stride,
    uint32_t k_descale_head_stride,
    uint32_t v_descale_batch_stride,
    uint32_t v_descale_head_stride,
    uint32_t b,
    uint32_t b_k,
    uint32_t h,
    uint32_t h_k,
    uint32_t d,
    uint32_t dv,
    uint32_t seqlen_q,
    uint32_t seqlen_k,
    uint32_t total_q,
    uint32_t total_k,
    float softmax_scale,
    int is_bf16,
    int is_e4m3,
    int window_size_left,
    int window_size_right,
    int attention_chunk,
    int page_size,
    uint32_t page_table_batch_stride,
    int num_pages,
    int num_splits,
    void *softmax_lseaccum_ptr,
    void *oaccum_ptr,
    uint32_t oaccum_split_stride,
    uint32_t oaccum_batch_stride,
    uint32_t oaccum_row_stride,
    uint32_t oaccum_head_stride,
    uint32_t lseaccum_split_stride,
    uint32_t lseaccum_batch_stride,
    uint32_t lseaccum_head_stride,
    float softcap,
    int pack_gqa,
    int64_t cu_stream
);
#endif

#ifndef FLASHATTENTION_DISABLE_SM90
extern "C" void run_mha_sm90(
    void *q_ptr,
    void *k_ptr,
    void *v_ptr,
    void *page_table_ptr,
    void *o_ptr,
    void *softmax_lse_ptr,
    int32_t *cu_seqlens_q_ptr,
    int32_t *cu_seqlens_k_ptr,
    int32_t *seqused_q_ptr,
    int32_t *seqused_k_ptr,
    int32_t *leftpad_k_ptr,
    int32_t *kv_batch_idx_ptr,
    float *q_descale_ptr,
    float *k_descale_ptr,
    float *v_descale_ptr,
    uint32_t q_batch_stride,
    uint32_t k_batch_stride,
    uint32_t v_batch_stride,
    uint32_t o_batch_stride,
    uint32_t q_row_stride,
    uint32_t k_row_stride,
    uint32_t v_row_stride,
    uint32_t o_row_stride,
    uint32_t q_head_stride,
    uint32_t k_head_stride,
    uint32_t v_head_stride,
    uint32_t o_head_stride,
    uint32_t v_dim_stride,
    uint32_t q_descale_batch_stride,
    uint32_t q_descale_head_stride,
    uint32_t k_descale_batch_stride,
    uint32_t k_descale_head_stride,
    uint32_t v_descale_batch_stride,
    uint32_t v_descale_head_stride,
    uint32_t b,
    uint32_t b_k,
    uint32_t h,
    uint32_t h_k,
    uint32_t d,
    uint32_t dv,
    uint32_t seqlen_q,
    uint32_t seqlen_k,
    uint32_t total_q,
    uint32_t total_k,
    float softmax_scale,
    int is_bf16,
    int is_e4m3,
    int window_size_left,
    int window_size_right,
    int attention_chunk,
    int page_size,
    uint32_t page_table_batch_stride,
    int num_pages,
    int num_splits,
    void *softmax_lseaccum_ptr,
    void *oaccum_ptr,
    uint32_t oaccum_split_stride,
    uint32_t oaccum_batch_stride,
    uint32_t oaccum_row_stride,
    uint32_t oaccum_head_stride,
    uint32_t lseaccum_split_stride,
    uint32_t lseaccum_batch_stride,
    uint32_t lseaccum_head_stride,
    float softcap,
    int pack_gqa,
    int64_t cu_stream
);

extern "C" void run_mha_sm90_softcap(
    void *q_ptr,
    void *k_ptr,
    void *v_ptr,
    void *page_table_ptr,
    void *o_ptr,
    void *softmax_lse_ptr,
    int32_t *cu_seqlens_q_ptr,
    int32_t *cu_seqlens_k_ptr,
    int32_t *seqused_q_ptr,
    int32_t *seqused_k_ptr,
    int32_t *leftpad_k_ptr,
    int32_t *kv_batch_idx_ptr,
    float *q_descale_ptr,
    float *k_descale_ptr,
    float *v_descale_ptr,
    uint32_t q_batch_stride,
    uint32_t k_batch_stride,
    uint32_t v_batch_stride,
    uint32_t o_batch_stride,
    uint32_t q_row_stride,
    uint32_t k_row_stride,
    uint32_t v_row_stride,
    uint32_t o_row_stride,
    uint32_t q_head_stride,
    uint32_t k_head_stride,
    uint32_t v_head_stride,
    uint32_t o_head_stride,
    uint32_t v_dim_stride,
    uint32_t q_descale_batch_stride,
    uint32_t q_descale_head_stride,
    uint32_t k_descale_batch_stride,
    uint32_t k_descale_head_stride,
    uint32_t v_descale_batch_stride,
    uint32_t v_descale_head_stride,
    uint32_t b,
    uint32_t b_k,
    uint32_t h,
    uint32_t h_k,
    uint32_t d,
    uint32_t dv,
    uint32_t seqlen_q,
    uint32_t seqlen_k,
    uint32_t total_q,
    uint32_t total_k,
    float softmax_scale,
    int is_bf16,
    int is_e4m3,
    int window_size_left,
    int window_size_right,
    int attention_chunk,
    int page_size,
    uint32_t page_table_batch_stride,
    int num_pages,
    int num_splits,
    void *softmax_lseaccum_ptr,
    void *oaccum_ptr,
    uint32_t oaccum_split_stride,
    uint32_t oaccum_batch_stride,
    uint32_t oaccum_row_stride,
    uint32_t oaccum_head_stride,
    uint32_t lseaccum_split_stride,
    uint32_t lseaccum_batch_stride,
    uint32_t lseaccum_head_stride,
    float softcap,
    int pack_gqa,
    int64_t cu_stream
);
#endif

extern "C" void run_mha(
    void *q_ptr,
    void *k_ptr,
    void *v_ptr,
    void *page_table_ptr,
    void *o_ptr,
    void *softmax_lse_ptr,
    int32_t *cu_seqlens_q_ptr,
    int32_t *cu_seqlens_k_ptr,
    int32_t *seqused_q_ptr,
    int32_t *seqused_k_ptr,
    int32_t *leftpad_k_ptr,
    int32_t *kv_batch_idx_ptr,
    float *q_descale_ptr,
    float *k_descale_ptr,
    float *v_descale_ptr,
    uint32_t q_batch_stride,
    uint32_t k_batch_stride,
    uint32_t v_batch_stride,
    uint32_t o_batch_stride,
    uint32_t q_row_stride,
    uint32_t k_row_stride,
    uint32_t v_row_stride,
    uint32_t o_row_stride,
    uint32_t q_head_stride,
    uint32_t k_head_stride,
    uint32_t v_head_stride,
    uint32_t o_head_stride,
    uint32_t v_dim_stride,
    uint32_t q_descale_batch_stride,
    uint32_t q_descale_head_stride,
    uint32_t k_descale_batch_stride,
    uint32_t k_descale_head_stride,
    uint32_t v_descale_batch_stride,
    uint32_t v_descale_head_stride,
    uint32_t b,
    uint32_t b_k,
    uint32_t h,
    uint32_t h_k,
    uint32_t d,
    uint32_t dv,
    uint32_t seqlen_q,
    uint32_t seqlen_k,
    uint32_t total_q,
    uint32_t total_k,
    float softmax_scale,
    int is_bf16,
    int is_e4m3,
    int window_size_left,
    int window_size_right,
    int attention_chunk,
    int page_size,
    uint32_t page_table_batch_stride,
    int num_pages,
    int num_splits,
    void *softmax_lseaccum_ptr,
    void *oaccum_ptr,
    uint32_t oaccum_split_stride,
    uint32_t oaccum_batch_stride,
    uint32_t oaccum_row_stride,
    uint32_t oaccum_head_stride,
    uint32_t lseaccum_split_stride,
    uint32_t lseaccum_batch_stride,
    uint32_t lseaccum_head_stride,
    float softcap,
    int pack_gqa,
    int64_t cu_stream
) {
    int device = 0;
    if (cudaGetDevice(&device) != cudaSuccess) {
        return;
    }
    cudaDeviceProp prop;
    if (cudaGetDeviceProperties(&prop, device) != cudaSuccess) {
        return;
    }
    int arch = prop.major * 10 + prop.minor;
    bool use_softcap = softcap > 0.0f;

#ifndef FLASHATTENTION_DISABLE_SM90
    if (arch >= 90 && arch <= 100) {
        if (use_softcap) {
            run_mha_sm90_softcap(
                q_ptr,
                k_ptr,
                v_ptr,
                page_table_ptr,
                o_ptr,
                softmax_lse_ptr,
                cu_seqlens_q_ptr,
                cu_seqlens_k_ptr,
                seqused_q_ptr,
                seqused_k_ptr,
                leftpad_k_ptr,
                kv_batch_idx_ptr,
                q_descale_ptr,
                k_descale_ptr,
                v_descale_ptr,
                q_batch_stride,
                k_batch_stride,
                v_batch_stride,
                o_batch_stride,
                q_row_stride,
                k_row_stride,
                v_row_stride,
                o_row_stride,
                q_head_stride,
                k_head_stride,
                v_head_stride,
                o_head_stride,
                v_dim_stride,
                q_descale_batch_stride,
                q_descale_head_stride,
                k_descale_batch_stride,
                k_descale_head_stride,
                v_descale_batch_stride,
                v_descale_head_stride,
                b,
                b_k,
                h,
                h_k,
                d,
                dv,
                seqlen_q,
                seqlen_k,
                total_q,
                total_k,
                softmax_scale,
                is_bf16,
                is_e4m3,
                window_size_left,
                window_size_right,
                attention_chunk,
                page_size,
                page_table_batch_stride,
                num_pages,
                num_splits,
                softmax_lseaccum_ptr,
                oaccum_ptr,
                oaccum_split_stride,
                oaccum_batch_stride,
                oaccum_row_stride,
                oaccum_head_stride,
                lseaccum_split_stride,
                lseaccum_batch_stride,
                lseaccum_head_stride,
                softcap,
                pack_gqa,
                cu_stream
            );
        } else {
            run_mha_sm90(
                q_ptr,
                k_ptr,
                v_ptr,
                page_table_ptr,
                o_ptr,
                softmax_lse_ptr,
                cu_seqlens_q_ptr,
                cu_seqlens_k_ptr,
                seqused_q_ptr,
                seqused_k_ptr,
                leftpad_k_ptr,
                kv_batch_idx_ptr,
                q_descale_ptr,
                k_descale_ptr,
                v_descale_ptr,
                q_batch_stride,
                k_batch_stride,
                v_batch_stride,
                o_batch_stride,
                q_row_stride,
                k_row_stride,
                v_row_stride,
                o_row_stride,
                q_head_stride,
                k_head_stride,
                v_head_stride,
                o_head_stride,
                v_dim_stride,
                q_descale_batch_stride,
                q_descale_head_stride,
                k_descale_batch_stride,
                k_descale_head_stride,
                v_descale_batch_stride,
                v_descale_head_stride,
                b,
                b_k,
                h,
                h_k,
                d,
                dv,
                seqlen_q,
                seqlen_k,
                total_q,
                total_k,
                softmax_scale,
                is_bf16,
                is_e4m3,
                window_size_left,
                window_size_right,
                attention_chunk,
                page_size,
                page_table_batch_stride,
                num_pages,
                num_splits,
                softmax_lseaccum_ptr,
                oaccum_ptr,
                oaccum_split_stride,
                oaccum_batch_stride,
                oaccum_row_stride,
                oaccum_head_stride,
                lseaccum_split_stride,
                lseaccum_batch_stride,
                lseaccum_head_stride,
                softcap,
                pack_gqa,
                cu_stream
            );
        }
        return;
    }
#endif

#ifndef FLASHATTENTION_DISABLE_SM80
    if (use_softcap) {
        run_mha_sm80_softcap(
            q_ptr,
            k_ptr,
            v_ptr,
            page_table_ptr,
            o_ptr,
            softmax_lse_ptr,
            cu_seqlens_q_ptr,
            cu_seqlens_k_ptr,
            seqused_q_ptr,
            seqused_k_ptr,
            leftpad_k_ptr,
            kv_batch_idx_ptr,
            q_descale_ptr,
            k_descale_ptr,
            v_descale_ptr,
            q_batch_stride,
            k_batch_stride,
            v_batch_stride,
            o_batch_stride,
            q_row_stride,
            k_row_stride,
            v_row_stride,
            o_row_stride,
            q_head_stride,
            k_head_stride,
            v_head_stride,
            o_head_stride,
            v_dim_stride,
            q_descale_batch_stride,
            q_descale_head_stride,
            k_descale_batch_stride,
            k_descale_head_stride,
            v_descale_batch_stride,
            v_descale_head_stride,
            b,
            b_k,
            h,
            h_k,
            d,
            dv,
            seqlen_q,
            seqlen_k,
            total_q,
            total_k,
            softmax_scale,
            is_bf16,
            is_e4m3,
            window_size_left,
            window_size_right,
            attention_chunk,
            page_size,
            page_table_batch_stride,
            num_pages,
            num_splits,
            softmax_lseaccum_ptr,
            oaccum_ptr,
            oaccum_split_stride,
            oaccum_batch_stride,
            oaccum_row_stride,
            oaccum_head_stride,
            lseaccum_split_stride,
            lseaccum_batch_stride,
            lseaccum_head_stride,
            softcap,
            pack_gqa,
            cu_stream
        );
    } else {
        run_mha_sm80(
            q_ptr,
            k_ptr,
            v_ptr,
            page_table_ptr,
            o_ptr,
            softmax_lse_ptr,
            cu_seqlens_q_ptr,
            cu_seqlens_k_ptr,
            seqused_q_ptr,
            seqused_k_ptr,
            leftpad_k_ptr,
            kv_batch_idx_ptr,
            q_descale_ptr,
            k_descale_ptr,
            v_descale_ptr,
            q_batch_stride,
            k_batch_stride,
            v_batch_stride,
            o_batch_stride,
            q_row_stride,
            k_row_stride,
            v_row_stride,
            o_row_stride,
            q_head_stride,
            k_head_stride,
            v_head_stride,
            o_head_stride,
            v_dim_stride,
            q_descale_batch_stride,
            q_descale_head_stride,
            k_descale_batch_stride,
            k_descale_head_stride,
            v_descale_batch_stride,
            v_descale_head_stride,
            b,
            b_k,
            h,
            h_k,
            d,
            dv,
            seqlen_q,
            seqlen_k,
            total_q,
            total_k,
            softmax_scale,
            is_bf16,
            is_e4m3,
            window_size_left,
            window_size_right,
            attention_chunk,
            page_size,
            page_table_batch_stride,
            num_pages,
            num_splits,
            softmax_lseaccum_ptr,
            oaccum_ptr,
            oaccum_split_stride,
            oaccum_batch_stride,
            oaccum_row_stride,
            oaccum_head_stride,
            lseaccum_split_stride,
            lseaccum_batch_stride,
            lseaccum_head_stride,
            softcap,
            pack_gqa,
            cu_stream
        );
    }
#else
    (void)use_softcap;
    (void)q_ptr;
    (void)k_ptr;
    (void)v_ptr;
    (void)page_table_ptr;
    (void)o_ptr;
    (void)softmax_lse_ptr;
    (void)cu_seqlens_q_ptr;
    (void)cu_seqlens_k_ptr;
    (void)seqused_q_ptr;
    (void)seqused_k_ptr;
    (void)leftpad_k_ptr;
    (void)kv_batch_idx_ptr;
    (void)q_descale_ptr;
    (void)k_descale_ptr;
    (void)v_descale_ptr;
    (void)q_batch_stride;
    (void)k_batch_stride;
    (void)v_batch_stride;
    (void)o_batch_stride;
    (void)q_row_stride;
    (void)k_row_stride;
    (void)v_row_stride;
    (void)o_row_stride;
    (void)q_head_stride;
    (void)k_head_stride;
    (void)v_head_stride;
    (void)o_head_stride;
    (void)v_dim_stride;
    (void)q_descale_batch_stride;
    (void)q_descale_head_stride;
    (void)k_descale_batch_stride;
    (void)k_descale_head_stride;
    (void)v_descale_batch_stride;
    (void)v_descale_head_stride;
    (void)b;
    (void)b_k;
    (void)h;
    (void)h_k;
    (void)d;
    (void)dv;
    (void)seqlen_q;
    (void)seqlen_k;
    (void)total_q;
    (void)total_k;
    (void)softmax_scale;
    (void)is_bf16;
    (void)is_e4m3;
    (void)window_size_left;
    (void)window_size_right;
    (void)attention_chunk;
    (void)page_size;
    (void)page_table_batch_stride;
    (void)num_pages;
    (void)num_splits;
    (void)softmax_lseaccum_ptr;
    (void)oaccum_ptr;
    (void)oaccum_split_stride;
    (void)oaccum_batch_stride;
    (void)oaccum_row_stride;
    (void)oaccum_head_stride;
    (void)lseaccum_split_stride;
    (void)lseaccum_batch_stride;
    (void)lseaccum_head_stride;
    (void)softcap;
    (void)pack_gqa;
    (void)cu_stream;
#endif
}
