use core::ffi::{c_int, c_void};

extern "C" {
    pub(crate) fn run_mha(
        q_ptr: *const c_void,
        k_ptr: *const c_void,
        v_ptr: *const c_void,
        page_table_ptr: *const c_void,
        o_ptr: *mut c_void,
        softmax_lse_ptr: *mut c_void,
        cu_seqlens_q_ptr: *const i32,
        cu_seqlens_k_ptr: *const i32,
        seqused_q_ptr: *const i32,
        seqused_k_ptr: *const i32,
        leftpad_k_ptr: *const i32,
        kv_batch_idx_ptr: *const i32,
        q_descale_ptr: *const f32,
        k_descale_ptr: *const f32,
        v_descale_ptr: *const f32,
        q_batch_stride: u32,
        k_batch_stride: u32,
        v_batch_stride: u32,
        o_batch_stride: u32,
        q_row_stride: u32,
        k_row_stride: u32,
        v_row_stride: u32,
        o_row_stride: u32,
        q_head_stride: u32,
        k_head_stride: u32,
        v_head_stride: u32,
        o_head_stride: u32,
        v_dim_stride: u32,
        q_descale_batch_stride: u32,
        q_descale_head_stride: u32,
        k_descale_batch_stride: u32,
        k_descale_head_stride: u32,
        v_descale_batch_stride: u32,
        v_descale_head_stride: u32,
        b: u32,
        b_k: u32,
        h: u32,
        h_k: u32,
        d: u32,
        dv: u32,
        seqlen_q: u32,
        seqlen_k: u32,
        total_q: u32,
        total_k: u32,
        softmax_scale: f32,
        is_bf16: c_int,
        is_e4m3: c_int,
        window_size_left: c_int,
        window_size_right: c_int,
        attention_chunk: c_int,
        page_size: c_int,
        page_table_batch_stride: u32,
        num_pages: c_int,
        num_splits: c_int,
        softmax_lseaccum_ptr: *mut c_void,
        oaccum_ptr: *mut c_void,
        oaccum_split_stride: u32,
        oaccum_batch_stride: u32,
        oaccum_row_stride: u32,
        oaccum_head_stride: u32,
        lseaccum_split_stride: u32,
        lseaccum_batch_stride: u32,
        lseaccum_head_stride: u32,
        softcap: f32,
        pack_gqa: c_int,
        cu_stream: i64,
    );
}
